name: Validate & Deploy
on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: "latest"

      - name: Install server & client dependencies
        run: bun run install-all

      - name: Build server & client
        run: bun run build-all

  docker:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v5

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./server
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/tacnamarket-server:latest

  deploy:
    runs-on: ubuntu-latest
    needs: docker
    steps:
      - name: Deploy on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          envs: GHCR_TOKEN,GITHUB_ACTOR
          script: |
            set -e
            echo "$GHCR_TOKEN" | docker login ghcr.io -u "$GITHUB_ACTOR" --password-stdin
            cd ~/projects/TacnaMarket
            git pull origin main
            docker pull ghcr.io/willianjc/tacnamarket-server:latest
            docker compose up -d
        env:
          GHCR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_ACTOR: ${{ github.actor }}
